=== etalii-adp/etalii.adp.ide.standalone/src/editors/xml/examples/library.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="library">
    <xs:annotation>
      <xs:documentation>A library: its name, then its books in shelf order.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="book" type="book" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation>One book on the shelf.</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="book">
    <xs:sequence>
      <xs:element name="title" type="xs:string"/>
      <xs:element name="author" type="xs:string" maxOccurs="unbounded"/>
      <xs:element name="year" type="xs:gYear">
        <xs:annotation>
          <xs:documentation>The year of first publication, as four digits.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="lent" type="xs:boolean" minOccurs="0"/>
      <xs:element name="signed" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Present when the copy is signed by its author.</xs:documentation>
        </xs:annotation>
        <xs:complexType/>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="isbn" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>The book's ISBN, with or without dashes.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="format" type="format"/>
  </xs:complexType>

  <xs:simpleType name="format">
    <xs:restriction base="xs:string">
      <xs:enumeration value="hardback"/>
      <xs:enumeration value="paperback"/>
      <xs:enumeration value="ebook"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== etalii-adp/etalii.adp.ide.standalone/src/editors/xml/examples/library.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- A small library that satisfies library.xsd. -->
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="library.xsd">
  <name>The reading room</name>
  <book isbn="978-0-14-118776-1" format="paperback">
    <title>Middlemarch</title>
    <author>George Eliot</author>
    <year>1871</year>
    <lent>false</lent>
  </book>
  <book isbn="978-0-19-953556-9" format="hardback">
    <title>The Moonstone</title>
    <author>Wilkie Collins</author>
    <year>1868</year>
    <signed/>
  </book>
</library>
